### ISSUE TITLE
Autocompletion doesn't take existing code into account

### ISSUE THREAD

**Issue by Mahi** [szensk/subllualove#10]
For example, if I write:
![love1.png](http://i.imgur.com/3THJU9t.png)
And hit enter, I will get the following:
![love2.png](http://i.imgur.com/BpFKJgp.png)
When obviously I wanted to get:

```
image = love.graphics.newImage(filename, format)
```

**Comment by dwexel** [comment]
I have the same issue. Is there any way to fix this, perhaps by disabling specific autocompletes?

**Comment by Aiq0** [comment]
The problem is, that this plugin autocompletes also return values of functions. There are 2 options:
1. Do not type image = love.graphi... but only love.grap... and then let it complete also return values, which you can then edit (press tab to edit next return value / function parameter, useful if you don't remember, what function returns)
2. Remove return values from autocomplete

I was thinking about implementing option 2 some time ago, when I was updating autocompletions for LÖVE 11.4, but I was afraid, if it wouldn't break user experience of some users, who use option 1.

I don't know about another way to fix this or if it would be possible to add this as option to settings (I don't think, there is Sublime API for this, while we are using `.sublime-completions` file and not suggesting completions thru Sublime API).

Maybe ask @szensk?

**Comment by szensk** [comment]
@Aiq0 I am not against option 2. 

Or
3. Implement on_query_completions and add completions based on a new setting. Seems like more work and the default setting would probably be equivalent to option 2 anyway.

**Comment by Aiq0** [comment]
So I remove all return values from autocompletions in 2.2.0 (along with other fixes, for which I forgot to create a release).
